# Generated by Django 6.1.1 on 2026-09-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=11),
            preserve_default=False,
        ),
    ]
