# Generated by Django 6.1.1 on 2026-09-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0002_remove_livro_ano_remove_livro_autor_livro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
