# Generated by Django 6.1.1 on 2026-09-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0003_livro_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
    ]
